---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.deriv.dev
  resources:
  - loglisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.deriv.dev
  resources:
  - loglisteners/finalizers
  verbs:
  - update
- apiGroups:
  - cache.deriv.dev
  resources:
  - loglisteners/status
  verbs:
  - get
  - patch
  - update
